# version: '3'

# services:
#   mysql:
#     image: mysql:latest
#     container_name: mysql
#     ports:
#       - '3308:3306'
#     environment:
#       - MYSQL_ROOT_PASSWORD=1
#       - MYSQL_PASSWORD=1
#       - MYSQL_DATABASE=database
#     command: --sql-mode=""
#     restart: always
